# ----------------------------------------------------------------------
# CONFIGURAÇÃO DO PROGRAMA DE ANÁLISE DE DADOS
# ----------------------------------------------------------------------
# Este arquivo contém as configurações do programa para carregar, processar
# e visualizar os dados de batidas. Ele é dividido em seções que configuram 
# colunas do Excel, parâmetros de análise, sliders, exportação e visualização.
# ----------------------------------------------------------------------

# Seção que mapeia as colunas do arquivo Excel para o DataFrame
excel_columns:
  date: 'DATA'                            # Coluna com a data
  cod_batida: 'COD. BATIDA'               # Coluna com o código da batida
  nome: 'NOME'                            # Coluna com o nome da dieta/atividade
  alimento: 'ALIMENTO'                    # Coluna com o nome do alimento
  tipo: 'TIPO'                            # Coluna com o tipo de alimento (para aplicar os pesos relativos)
  previsto: 'PREVISTO (KG)'               # Coluna com a quantidade prevista (primeira instância)
  previsto_dup: 'PREVISTO (KG).1'         # Coluna duplicada de quantidade prevista
  realizado: 'REALIZADO (KG)'             # Coluna com a quantidade realizada (primeira instância)
  realizado_dup: 'REALIZADO (KG).1'       # Coluna duplicada de quantidade realizada
  diferenca_percentual: 'DIFERENÇA (%)'   # Coluna com a diferença percentual entre o previsto e o realizado
  operator: 'OPERADOR'                    # Coluna com o operador responsável
  motorista: 'MOTORISTA'                  # Coluna com o motorista (se aplicável)

# ----------------------------------------------------------------------
# CONFIGURAÇÃO DOS PARÂMETROS DE ANÁLISE
# ----------------------------------------------------------------------
analysis:
  default_weight: 1.0                     # Peso padrão inicial para os sliders de alimentos
  tolerance_threshold: 3                  # Limite de tolerância em % para a análise de diferenças
  outlier_threshold: 1.5                  # Limite para definir outliers (em desvio interquartil)
  skip_rows: 2                            # Número de linhas a serem puladas ao carregar o arquivo Excel
  remove_first_column: true               # Indica se a primeira coluna do Excel deve ser removida (geralmente índice)

# ----------------------------------------------------------------------
# CONFIGURAÇÃO DOS SLIDERS DE PESOS RELATIVOS
# ----------------------------------------------------------------------
slider:
  min_value: 0.5                          # Valor mínimo permitido para os sliders
  max_value: 5.0                          # Valor máximo permitido para os sliders
  step: 0.1                               # Incremento de ajuste para os sliders (precisão)

# ----------------------------------------------------------------------
# CONFIGURAÇÃO DA MÉDIA PONDERADA (CÁLCULOS)
# ----------------------------------------------------------------------
weighted_average:
  previsto_column: 'PREVISTO (KG)'        # Coluna principal de valor previsto
  realizado_column: 'REALIZADO (KG)'      # Coluna principal de valor realizado
  diferenca_percentual_column: 'DIFERENÇA (%)'  # Coluna de diferença percentual
  pesos_relativos_column: 'TIPO'          # Coluna usada para os pesos relativos
  peso_multiplicador: true                # Se True, multiplica o peso pelo valor previsto
  peso_relativo: 1.0                      # Multiplicador global dos pesos relativos
  outlier_threshold: 1.5                  # Limite para remoção de outliers (mesmo valor de "analysis")

# ----------------------------------------------------------------------
# CONFIGURAÇÃO DA INTERFACE DO USUÁRIO
# ----------------------------------------------------------------------
ui:
  page_title: "Análise de Dados - Histograma"    # Título da página na interface web
  layout: "wide"                                 # Layout da página (wide, centered, etc.)
  file_uploader:
    label: "Escolha o arquivo Excel (.xlsx)"     # Texto de instrução para o upload do arquivo Excel
    allowed_types: ["xlsx"]                      # Tipos de arquivo permitidos para upload
  analysis_config_header: "Configurações da Análise"  # Cabeçalho da seção de configuração
  food_weights_subheader: "Pesos relativos"      # Texto dos sliders
  date_input:
    label: "Selecione o período:"                # Texto de instrução para seleção de datas
  multiselect:
    food_label: "Escolha os Alimentos:"          # Texto de instrução para selecionar alimentos
    diet_label: "Escolha as Dietas:"             # Texto de instrução para selecionar dietas
    operator_label: "Escolha os Operadores:"     # Texto de instrução para selecionar operadores
  remove_outliers:
    label: "Remover outliers do histograma"      # Texto de instrução para remover outliers
    help: "Remover valores extremos que podem distorcer a análise."  # Texto de ajuda sobre outliers
  generate_button: "Gerar"                       # Texto do botão de geração de resultados
  results_header: "Resultados da Análise - Confinamento"  # Título da seção de resultados
  statistics_title: "### Estatísticas principais" # Título da seção de estatísticas
  ui:
  results_header: "Resultados da Análise"
  statistics_title: "Estatísticas Principais das Diferenças Percentuais"
  food_weights_subheader: "Pesos Relativos"
  outliers_removed_message: "Outliers foram removidos do histograma para melhor visualização."  # Mensagem ao remover outliers

# ----------------------------------------------------------------------
# CONFIGURAÇÃO DA VISUALIZAÇÃO DO HISTOGRAMA
# ----------------------------------------------------------------------
visualization:
  histogram_figsize: [12, 8]                     # Tamanho do histograma (figura) em polegadas
  histogram_title: "Distribuição da Média Ponderada da Diferença Percentual - Confinamento"  # Título do histograma
  color_threshold: 3                             # Limite de cor para destacar barras específicas
  grid_style:
    axis: 'y'                                    # Eixo da grade (pode ser x ou y)
    linestyle: '--'                              # Estilo das linhas da grade (tracejado)
    linewidth: 0.7                               # Espessura das linhas da grade
  vertical_line:
    color: 'green'                               # Cor da linha vertical no histograma
    linestyle: '--'                              # Estilo da linha vertical
    linewidth: 2                                 # Espessura da linha vertical
    label: "Tolerância Máxima"                   # Texto da legenda da linha vertical

  # Configuração da legenda
  legend:
    location: 'upper right'                      # Localização da legenda no gráfico
    fontsize: 8                                  # Tamanho da fonte da legenda
    frameon: true                                # Exibir borda ao redor da legenda
    facecolor: 'lightgreen'                      # Cor de fundo da legenda
    edgecolor: 'black'                           # Cor da borda da legenda
    fancybox: true                               # Bordas arredondadas na caixa da legenda
    framealpha: 0.5                              # Transparência da legenda
    bbox_to_anchor: [0.91, 0.9]                  # Posição exata da legenda no gráfico

  weights_table:
    position: [0.9, 0.70]                        # Posição da tabela de pesos no gráfico
    fontsize: 8                                  # Tamanho da fonte da tabela de pesos
    facecolor: 'lightgrey'                       # Cor de fundo da tabela de pesos
    alpha: 0.5                                   # Transparência da tabela de pesos
    boxstyle: 'round,pad=0.5'                    # Estilo da caixa ao redor da tabela de pesos

  footer:
    fontsize: 10                                 # Tamanho da fonte do rodapé do gráfico

  subplot_adjust:
    left: 0.05                                   # Ajuste da margem esquerda do gráfico
    right: 0.95                                  # Espaço para a tabela de pesos
    bottom: 0.1                                  # Ajuste da margem inferior
    top: 0.9                                     # Ajuste da margem superior

# ----------------------------------------------------------------------
# CONFIGURAÇÃO DE EXPORTAÇÃO
# ----------------------------------------------------------------------
export:
  histogram:
    format: "png"                                # Formato do arquivo exportado (imagem do histograma)
    dpi: 300                                     # Resolução da imagem exportada
  statistics:
    format: "csv"                                # Formato do arquivo exportado para as estatísticas

# ----------------------------------------------------------------------
# CONFIGURAÇÃO DE TIMEZONE
# ----------------------------------------------------------------------
timezone: "America/Sao_Paulo"                    # Definição do fuso horário para os dados
